import{useState} from 'react';
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Intro from "../images/intro.svg";
import Send from "../images/send.svg";
import Connect from "../images/connect.svg";
import Support from "../images/icons/support.svg";
import Speed from "../images/icons/speed.svg";
import Security from "../images/icons/security.svg";
import Accuracy from "../images/icons/accuracy.svg";
import Navbar from "../components/navbar";
import Footer from "../components/footer";

export default function Home() {

  const [showNav, setShowNav] = useState(false);
  
  return (
    <div className={showNav?`index-container index-container--hidden`:`index-container`}>
      <Head>
        <title>Bundle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='../images/logo-2.svg' />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="index-main">
        <Navbar showNav={showNav} setShowNav={setShowNav}/>

        <div className="main-intro">
          <div className="intro__text">
            <h2>
              Keep track of your transactions, all in <b>one place!</b>
            </h2>
            <p>
              We help our customers seamlessly monitor their transactions across
              all accounts while providing added features.
            </p>
            <Link href="./signup"><button>Get Started</button></Link>
          </div>

          <div className="intro__image">
            <Image src={Intro} alt="amico" />
          </div>
        </div>

        <div className="main-connect">
          <div className="connect__image">
            <Image src={Connect} alt="connect" />
          </div>

          <div className="connect__text">
            <h3>Connect all your accounts on one platform</h3>
            <p>You don’t have to login to different platforms every time</p>
            <Link href="./signup"><button>Learn More</button></Link>
          </div>
        </div>

        <div className="main-send">
          <div className="send__text">
            <h3>Send and request for statements easily</h3>
            <p>
              Easily get your account statements, send or even request account
              statements from others!
            </p>
            <Link href="./signup"><button>Learn More</button></Link>
          </div>

          <div className="send__image">
            <Image src={Send} alt="send and receive" />
          </div>
        </div>

        <div className="main-why-us">
          <div className="why-us__cards">
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Security} alt="security" />
              </div>
              <h5>Security</h5>
            </div>
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Speed} alt="speed" />
              </div>
              <h5>Speed</h5>
            </div>
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Accuracy} alt="accuracy" />
              </div>
              <h5>Accuracy</h5>
            </div>
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Support} alt="24/7 support" />
              </div>
              <h5>24/7 Support</h5>
            </div>
          </div>

          <div className="why-us__text">
            <h3>Why choose us?</h3>
            <p>
            We deliver accurately and timely while ensuring that every information you give us access to is safe and secure. We are also available if you need help!

            </p>
          </div>
        </div>

        <div className="join-us">
          <div className="join-us-box">
            <h3>Ready to join us?</h3>
            <Link href="./signup">
              <button>Get Started</button>
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
