import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Intro from "../images/intro.svg";
import Send from "../images/send.svg";
import Connect from "../images/connect.svg";
import Support from "../images/icons/support.svg";
import Speed from "../images/icons/speed.svg";
import Security from "../images/icons/security.svg";
import Accuracy from "../images/icons/accuracy.svg";
import Preloader from "../components/preloader";
import Navbar from "../components/navbar";
import Footer from "../components/footer";
import { motion, AnimatePresence } from "framer-motion";

export default function Home() {
  const [showNav, setShowNav] = useState(false);
  const [showPreloader, setShowPreloader] = useState(true);

  setTimeout(() => {
    setShowPreloader(false);
  }, 5000);

  return (
    <div
      className={
        showNav ? `index-container index-container--hidden` : `index-container`
      }
    >
      <Head>
        <title>Bundle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../images/logo-2.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      <main className="index-main">
        <AnimatePresence>
          {showPreloader ? <Preloader /> : null}
        </AnimatePresence>
        <Navbar showNav={showNav} setShowNav={setShowNav} />

        <div className="main-intro">
          <div className="intro__text">
            <motion.h2
              initial={{ opacity: 0, y: 150 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeIn" }}
            >
              Keep track of your transactions, all in <b>one place!</b>
            </motion.h2>
            <motion.p
              initial={{ opacity: 0, y: 60 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeInOut", delay: 0.2 }}
            >
              We help our customers seamlessly monitor their transactions across
              all accounts while providing added features.
            </motion.p>
            <Link href="./signup">
              <motion.button
                initial={{ opacity: 0, y: 60 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, ease: "easeInOut", delay: 0.4 }}
              >
                Get Started
              </motion.button>
            </Link>
          </div>

          <div className="intro__image">
            <Image src={Intro} alt="amico" />
          </div>
        </div>

        <div className="main-connect">
          <div className="connect__image">
            <Image src={Connect} alt="connect" />
          </div>

          <div className="connect__text">
            <motion.h3
              initial={{ opacity: 0, y: 150 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeIn" }}
            >
              Connect all your accounts on one platform
            </motion.h3>
            <motion.p
              initial={{ opacity: 0, y: 60 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeInOut", delay: 0.2 }}
            >
              You don’t have to login to different platforms every time
            </motion.p>
            <Link href="./signup">
              <motion.button
                initial={{ opacity: 0, y: 60 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, ease: "easeInOut", delay: 0.4 }}
              >
                Learn More
              </motion.button>
            </Link>
          </div>
        </div>

        <div className="main-send">
          <div className="send__text">
            <motion.h3
              initial={{ opacity: 0, y: 150 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeIn" }}
            >
              Send and request for statements easily
            </motion.h3>
            <motion.p
              initial={{ opacity: 0, y: 60 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeInOut", delay: 0.2 }}
            >
              Easy access to all your account statements. Send or Receive payments
              and account statements from others
            </motion.p>
            <Link href="./signup">
              <motion.button
                initial={{ opacity: 0, y: 60 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, ease: "easeInOut", delay: 0.4 }}
              >
                Learn More
              </motion.button>
            </Link>
          </div>

          <div className="send__image">
            <Image src={Send} alt="send and receive" />
          </div>
        </div>

        <div className="main-why-us">
          <div className="why-us__cards">
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Security} alt="security" />
              </div>
              <h5>Security</h5>
            </div>
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Speed} alt="speed" />
              </div>
              <h5>Speed</h5>
            </div>
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Accuracy} alt="accuracy" />
              </div>
              <h5>Accuracy</h5>
            </div>
            <div className="why-us__card">
              <div className="why-us__card__image">
                <Image src={Support} alt="24/7 support" />
              </div>
              <h5>24/7 Support</h5>
            </div>
          </div>

          <div className="why-us__text">
            <motion.h3
              card
              initial={{ opacity: 0, y: 150 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeIn" }}
            >
              Why choose us?
            </motion.h3>
            <motion.p
              initial={{ opacity: 0, y: 60 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, ease: "easeInOut", delay: 0.2 }}
            >
              Accurate and timely delivery ensuring your information is safe 
              and secure. We provide 24/7 support to ensure you have the best
            </motion.p>
          </div>
        </div>

        <div className="join-us">
          <div className="join-us-box">
            <h3>Ready to join us?</h3>
            <Link href="./signup">
              <button>Get Started</button>
            </Link>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
